
import React from 'react';
import { 
  Cloud, 
  Code, 
  RefreshCcw, 
  Database, 
  Cpu, 
  Settings, 
  CheckCircle, 
  Users, 
  TrendingUp, 
  ShieldCheck,
  Zap,
  Globe,
  Lock,
  MessageSquare,
  Award
} from 'lucide-react';
import { Service, NavItem, Testimonial, TeamMember, BlogPost, FAQItem } from './types';

export const NAV_ITEMS: NavItem[] = [
  { name: 'Home', path: '/' },
  { name: 'Services', path: '/services' },
  { name: 'Pricing', path: '/pricing' },
  { name: 'About', path: '/about' },
  { name: 'Blog', path: '/blog' },
  { name: 'FAQ', path: '/faq' },
  { name: 'Contact', path: '/contact' },
];

export const SERVICES: Service[] = [
  {
    id: 'implementation',
    icon: <Cloud className="w-8 h-8" />,
    title: 'Salesforce Implementation',
    shortDescription: 'Expert setup of Sales, Service, and Experience Clouds to drive business efficiency.',
    fullDescription: 'A successful Salesforce implementation is about more than just technology—it\'s about aligning your CRM with your business goals. We specialize in end-to-end implementation of Sales Cloud, Service Cloud, and Experience Cloud. Our methodology ensures that your team adopts the platform quickly and effectively through tailored configuration and comprehensive training.',
    process: ['Discovery & Requirements', 'Environment Configuration', 'User Acceptance Testing', 'Final Launch & Hypercare'],
    timeline: '4-12 weeks',
    pricing: 'Starting at $10,000',
    benefits: ['Faster deployment times', 'Industry best practices', 'High user adoption rates'],
  },
  {
    id: 'development',
    icon: <Code className="w-8 h-8" />,
    title: 'Custom Development',
    shortDescription: 'Tailored Apex and LWC solutions with advanced Flow automation for unique workflows.',
    fullDescription: 'When out-of-the-box features aren\'t enough, our development team steps in. We build high-performance Lightning Web Components (LWC), robust Apex triggers, and complex Flow automations that transform standard Salesforce into a custom-built power engine. We focus on scalable code that avoids technical debt.',
    process: ['Technical Architecture', 'Sprint Development', 'Security Review', 'Automated Deployment'],
    timeline: 'Agile Sprints',
    pricing: 'Request a custom quote',
    benefits: ['Bespoke functionality', 'Enterprise scalability', 'Clean, documented code'],
  },
  {
    id: 'integration',
    icon: <RefreshCcw className="w-8 h-8" />,
    title: 'Integration Services',
    shortDescription: 'Seamlessly connect Salesforce with ERP, Marketing, and Accounting systems.',
    fullDescription: 'Siloed data is the enemy of productivity. We build seamless integrations between Salesforce and your existing tech stack, including SAP, NetSuite, Marketo, QuickBooks, and Shopify. Whether via direct REST/SOAP APIs or middleware like MuleSoft, we ensure your data flows smoothly and accurately.',
    process: ['System Mapping', 'API Development', 'Data Validation', 'Sync Monitoring'],
    timeline: '6-14 weeks',
    pricing: 'Starting at $15,000',
    benefits: ['Unified data view', 'Real-time synchronization', 'Eliminated manual entry'],
  },
  {
    id: 'migration',
    icon: <Database className="w-8 h-8" />,
    title: 'Data Migration',
    shortDescription: 'Legacy CRM migration and data cleaning with zero downtime and total accuracy.',
    fullDescription: 'Moving to Salesforce should be painless. We handle complex data migrations from Excel, legacy CRMs, and SQL databases. Our process includes deep data cleansing, deduplication, and mapping to ensure your new Salesforce instance starts with pristine, reliable information.',
    process: ['Data Audit', 'Cleansing & Deduplication', 'Trial Import', 'Full Production Sync'],
    timeline: '2-6 weeks',
    pricing: 'Starting at $5,000',
    benefits: ['100% data integrity', 'Zero downtime transition', 'Simplified structures'],
  },
  {
    id: 'ai-solutions',
    icon: <Cpu className="w-8 h-8" />,
    title: 'AI & Agentforce',
    shortDescription: 'Leverage Einstein and Agentforce for predictive analytics and autonomous bots.',
    fullDescription: 'Step into the future with Salesforce AI. We implement Einstein Analytics and Agentforce to bring predictive insights and autonomous agents into your workflow. From sentiment analysis to automated customer service agents using the Atlas Reasoning Engine, we help you lead the AI revolution.',
    process: ['AI Strategy Planning', 'Data Foundation Build', 'Model Training', 'Autonomous Agent Launch'],
    timeline: '8-16 weeks',
    pricing: 'Starting at $20,000',
    benefits: ['Proactive decision making', '24/7 autonomous support', 'Hyper-personalization'],
  },
  {
    id: 'managed-services',
    icon: <Settings className="w-8 h-8" />,
    title: 'Managed Services',
    shortDescription: 'Ongoing optimization and support to keep your Salesforce instance at peak performance.',
    fullDescription: 'Salesforce is an evolving platform. Our managed services provide monthly retainers for ongoing optimization, release management (Spring, Summer, Winter), and on-demand user support. We act as your fractional Salesforce admin and development team, ensuring long-term success.',
    process: ['Health Check', 'Monthly Roadmapping', 'Standard Support', 'Release Planning'],
    timeline: 'Monthly Retainer',
    pricing: 'Custom Packages',
    benefits: ['Fixed monthly costs', 'Reduced technical debt', 'Continuous innovation'],
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    name: 'Sarah Jenkins',
    title: 'COO',
    company: 'FinTech Dynamics',
    content: 'SalesforceTroopAi transformed our sales process. Our team productivity increased by 40% within the first three months of implementation.',
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200&h=200',
  },
  {
    name: 'Michael Chen',
    title: 'Director of IT',
    company: 'Global Retail Solutions',
    content: 'The AI integration they provided via Agentforce has been a game changer for our customer service department. Highly professional and deeply technical.',
    photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200&h=200',
  },
];

export const TEAM: TeamMember[] = [
  {
    name: 'Alex Thompson',
    title: 'CEO & Founder',
    bio: '15 years of Salesforce architecture experience with a passion for leveraging AI to solve complex enterprise problems.',
    photo: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=800&h=1000',
  },
  {
    name: 'Priya Sharma',
    title: 'CTO',
    bio: 'Salesforce CTA specializing in complex integrations and autonomous agent development within the Einstein Trust Layer.',
    photo: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&q=80&w=800&h=1000',
  },
  {
    name: 'David Wilson',
    title: 'Lead Consultant',
    bio: 'Expert in business process mapping and ensuring that multi-cloud implementations align with C-level strategic objectives.',
    photo: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=800&h=1000',
  },
  {
    name: 'Elena Rodriguez',
    title: 'Customer Success',
    bio: 'Dedicated to maximizing ROI and user adoption across our portfolio of global mid-market and enterprise clients.',
    photo: 'https://images.unsplash.com/photo-1598550874175-4d0fe4a2c906?auto=format&fit=crop&q=80&w=800&h=1000',
  },
];

export const FAQS: FAQItem[] = [
  // General (8)
  { category: 'General', question: 'What is SalesforceTroopAi?', answer: 'We are a premier Salesforce consulting partner specializing in AI-driven digital transformation, implementation, and custom development.' },
  { category: 'General', question: 'Are you a certified Salesforce Partner?', answer: 'Yes, we are official Salesforce Certified Partners with over 50+ individual certifications across our core architect team.' },
  { category: 'General', question: 'Do you offer project rescue services?', answer: 'Absolutely. We specialize in auditing and fixing Salesforce instances that were poorly implemented or have high technical debt.' },
  { category: 'General', question: 'Where is your team based?', answer: 'We are a remote-first team with hubs in North America and Europe, allowing us to provide 24/7 support for global enterprises.' },
  { category: 'General', question: 'What industries do you serve?', answer: 'While platform-agnostic, we have deep expertise in FinTech, Healthcare (Health Cloud), High-Tech SaaS, and Professional Services.' },
  { category: 'General', question: 'How do you handle data security?', answer: 'We operate strictly within Salesforce security best practices and are happy to sign NDAs and work within your SOC2/HIPAA compliance frameworks.' },
  { category: 'General', question: 'Can I verify your credentials?', answer: 'Yes, we provide Trailblazer.me verification links for all lead architects assigned to your project during the discovery phase.' },
  { category: 'General', question: 'Do you help with license selection?', answer: 'Yes. We often save clients 15-20% on their Salesforce bill by ensuring they only buy the specific licenses and SKUs they actually need.' },

  // Services (8)
  { category: 'Services', question: 'What is Agentforce?', answer: 'Agentforce is Salesforce\'s autonomous AI platform. We use it to build agents that handle tasks like customer service and sales scheduling without human intervention.' },
  { category: 'Services', question: 'LWC vs. Standard Flow?', answer: 'We prefer a "Clicks not Code" approach with Flow for maintainability, using LWC only for high-performance custom UI or complex requirements.' },
  { category: 'Services', question: 'Do you support Marketing Cloud?', answer: 'Yes, we provide full implementation and strategy for Marketing Cloud Engagement, Account Engagement (Pardot), and Data Cloud.' },
  { category: 'Services', question: 'Can you integrate legacy ERPs?', answer: 'Yes. We have integrated Salesforce with SAP, Oracle, NetSuite, and custom on-premise systems using MuleSoft or custom REST APIs.' },
  { category: 'Services', question: 'What is your data migration process?', answer: 'We follow a 4-step Audit-Clean-Map-Validate process to ensure 100% data integrity with zero downtime for your users.' },
  { category: 'Services', question: 'Do you provide end-user training?', answer: 'Yes. Every implementation includes recorded workshops, "Train the Trainer" sessions, and custom user manuals.' },
  { category: 'Services', question: 'Is Health Cloud different?', answer: 'Yes. Health Cloud is a specialized CRM for healthcare. We implement it with strict adherence to patient privacy and clinical workflows.' },
  { category: 'Services', question: 'How do you handle DevOps?', answer: 'We use modern tools like Copado, Gearset, or GitHub Actions to ensure code is properly tested in sandboxes before hitting production.' },

  // Pricing (8)
  { category: 'Pricing', question: 'How much does a project cost?', answer: 'Implementations typically range from $10k (Starter) to $75k+ (Professional/Enterprise) depending on complexity and cloud count.' },
  { category: 'Pricing', question: 'Do you offer fixed-fee pricing?', answer: 'Yes. For implementations, we prefer fixed-fee engagements to provide you with budget certainty. Support is usually on a monthly retainer.' },
  { category: 'Pricing', question: 'What is in a Managed Services retainer?', answer: 'A block of hours for fractional administration, bug fixes, release management, and new feature development.' },
  { category: 'Pricing', question: 'Are there hidden costs?', answer: 'No. Our quotes cover all consulting hours. The only other costs are your Salesforce licenses and any 3rd party AppExchange tools.' },
  { category: 'Pricing', question: 'How do you handle scope creep?', answer: 'If requirements change significantly, we document them in a Change Request with clear pricing before any work begins.' },
  { category: 'Pricing', question: 'Do you offer non-profit discounts?', answer: 'Yes. We are proud supporters of the Salesforce.org "Power of Us" program and offer special rates for 501(c)(3) organizations.' },
  { category: 'Pricing', question: 'What is your payment schedule?', answer: 'Typically 40% at signing, 40% at UAT/Midpoint, and 20% at go-live/sign-off.' },
  { category: 'Pricing', question: 'Is the strategy call free?', answer: 'Yes. Our initial 30-minute consultation is free and comes with a high-level roadmap for your consideration.' },

  // Support (8)
  { category: 'Support', question: 'What is post-launch Hypercare?', answer: 'A 30-day period of dedicated support after go-live to ensure users are comfortable and any minor bugs are squashed immediately.' },
  { category: 'Support', question: 'What are your SLA response times?', answer: 'For managed services, we offer 4h response for critical issues and 48h for standard requests.' },
  { category: 'Support', question: 'Do I get a dedicated Project Manager?', answer: 'Yes. Every project has a PM who ensures timelines, budgets, and communication are managed flawlessly.' },
  { category: 'Support', question: 'Can you work in our Slack/Jira?', answer: 'Yes. We prefer to integrate into your existing communication and PM tools for seamless collaboration.' },
  { category: 'Support', question: 'How do you handle Salesforce releases?', answer: 'We review the 3 yearly release notes (Spring/Summer/Winter) for you and ensure your custom code remains compliant.' },
  { category: 'Support', question: 'Do you offer 24/7 support?', answer: 'Standard support is business hours, but we offer 24/7 mission-critical coverage for global enterprise clients as an add-on.' },
  { category: 'Support', question: 'Can you train my new internal admin?', answer: 'Yes. We often help clients transition from consulting to internal management by mentoring their new hires.' },
  { category: 'Support', question: 'What is "platform grit"?', answer: 'It refers to the technical debt and governor limit issues that accumulate. We handle the deep cleaning to keep your org healthy.' },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'agentforce-evolution',
    title: 'Agentforce: The New Era of Salesforce AI',
    excerpt: 'Discover how autonomous agents are changing the customer service and sales landscape forever.',
    date: 'Feb 02, 2025',
    author: 'Priya Sharma',
    readTime: '12 min read',
    image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=1200&h=600',
    category: 'AI & Innovation',
    tags: ['AI', 'Agentforce', 'Einstein'],
    isFeatured: true,
    content: `<h2>Beyond Chatbots: Meet Agentforce</h2><p>In 2025, Salesforce shifted the paradigm from Copilots to Autonomous Agents. Agentforce allows the Atlas Reasoning Engine to decide on the best course of action using your secure data.</p>`,
  },
  {
    id: 'implementation-guide-2025',
    title: 'Salesforce Implementation Guide 2025',
    excerpt: 'Master the complexities of a modern Salesforce rollout with our comprehensive framework.',
    date: 'Jan 15, 2025',
    author: 'Alex Thompson',
    readTime: '10 min read',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800&h=400',
    category: 'Strategy',
    tags: ['Implementation', 'Best Practices'],
    content: `<h2>The Strategic Blueprint</h2><p>Successful implementation requires a discovery-first approach. We break down the 4-phase rollout strategy for 2025.</p>`,
  },
  {
    id: 'roi-milestones',
    title: 'ROI Milestones: Your First 12 Months',
    excerpt: 'A data-backed breakdown of the costs, gains, and milestones you should target in year one.',
    date: 'Feb 10, 2025',
    author: 'David Wilson',
    readTime: '8 min read',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800&h=400',
    category: 'Strategy',
    tags: ['ROI', 'Analytics'],
    content: `<h2>Measuring Value</h2><p>Expect process efficiency in Q1 and predictive growth indicators by Q4. Here is the breakdown.</p>`,
  },
  {
    id: 'mastering-apex',
    title: 'Mastering Apex: Patterns for Enterprise Scale',
    excerpt: 'Elevate your code quality with robust patterns including Selector and Service layers.',
    date: 'Feb 20, 2025',
    author: 'Priya Sharma',
    readTime: '15 min read',
    image: 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?auto=format&fit=crop&q=80&w=800&h=400',
    category: 'Technical',
    tags: ['Apex', 'Architecture'],
    content: `<h2>Clean Enterprise Code</h2><p>Technical debt is an organizational killer. We explore the Service layer pattern in depth.</p>`,
  },
  {
    id: 'data-cloud-360',
    title: 'Data Cloud: The Unified Customer 360',
    excerpt: 'Learn how to harmonize disparate data sources for hyper-personalized experiences.',
    date: 'Mar 01, 2025',
    author: 'Elena Rodriguez',
    readTime: '11 min read',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=80&w=800&h=400',
    category: 'Technical',
    tags: ['Data Cloud', 'Customer 360'],
    content: `<h2>Real-Time Harmonization</h2><p>Data Cloud isn't just another database; it's a synchronization engine for the entire enterprise.</p>`,
  },
  {
    id: 'org-governance',
    title: 'Multi-Org vs Single-Org: The Governance Choice',
    excerpt: 'A strategic analysis of organizational architecture for global enterprises.',
    date: 'Mar 05, 2025',
    author: 'Alex Thompson',
    readTime: '9 min read',
    image: 'https://images.unsplash.com/photo-1454165833767-02a6ed8a4f81?auto=format&fit=crop&q=80&w=800&h=400',
    category: 'Platform Governance',
    tags: ['Architecture', 'Governance'],
    content: `<h2>The Architectural North Star</h2><p>Your choice of Org strategy defines your IT agility for the next 5 years.</p>`,
  },
  {
    id: 'lwc-performance',
    title: 'Extreme LWC Performance: Tips from the Field',
    excerpt: 'Optimize your custom UI with advanced caching and reactive property management.',
    date: 'Mar 10, 2025',
    author: 'Priya Sharma',
    readTime: '13 min read',
    image: 'https://images.unsplash.com/photo-1587620962725-abab7fe55159?auto=format&fit=crop&q=80&w=800&h=400',
    category: 'Technical',
    tags: ['LWC', 'JavaScript'],
    content: `<h2>High Performance UI</h2><p>Leverage wire adapters and the Lightning Data Service to build interfaces that feel instantaneous.</p>`,
  },
];
